//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpSDK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pageinexinfo
    {
        public int Id { get; set; }
        public string FriendsImages { get; set; }
        public string Description { get; set; }
        public Nullable<int> SharesRequirements { get; set; }
        public string AdImages { get; set; }
        public string AdURL { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public Nullable<int> shareinfoID { get; set; }
        public Nullable<System.DateTime> InputDate { get; set; }
        public string friendimages { get; set; }
    }
}
