//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpSDK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShareInfo
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string ShareURL { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public Nullable<System.DateTime> InputDate { get; set; }
    }
}
