//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpSDK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShareLog
    {
        public int Id { get; set; }
        public string userID { get; set; }
        public string shareUrl { get; set; }
        public Nullable<int> shareinfoID { get; set; }
        public string BrowseType { get; set; }
        public string ClientIp { get; set; }
        public Nullable<int> IsMobile { get; set; }
        public string OsName { get; set; }
        public string BrowseName { get; set; }
        public string BrowseVersion { get; set; }
        public string Country { get; set; }
        public string Area { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public string County { get; set; }
        public string Isp { get; set; }
        public Nullable<System.DateTime> InputDate { get; set; }
    }
}
